
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import project.InsertUpdateDelete;
import project.Podaci;
import project.Select;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class izvrsene_rezervacije extends javax.swing.JFrame {

    /**
     * Creates new form izvrsene_rezervacije
     */
    public izvrsene_rezervacije() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Vrsta smjestaja", "Lokacija", "Cijena", "Datum dolaska", "Datum odlaska", "Izdavac"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 770, 150));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Vrsta smjestaja", "Lokacija", "Cijena", "Datum dolaska", "Datum odlaska", "Izdavac"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 770, 150));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/strelica.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clo.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 40, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Potvrđene rezervacije");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Završene rezervacije");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/z9FxcE.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int a= JOptionPane.showConfirmDialog(null, "Da li stvarno želite izaći?","Izaberite",JOptionPane.YES_NO_OPTION);
        if(a==0)
            System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet rs1 = Select.getData("Select rezervacija.id_rezervacija, smjestaj.vrsta_smjestaja, smjestaj.lokacija, smjestaj.cijena, rezervacija.check_in, rezervacija.check_out, izdavac.username from rezervacija join smjestaj on rezervacija.id_smjestaj = smjestaj.id_smjestaj join izdavac on smjestaj.id_izdavac = izdavac.id_izdavac where rezervacija.potvrda = '1' and DATEDIFF(CURDATE(), rezervacija.check_in) < 0 and rezervacija.id_korisnik = " + Podaci.getId());
        DefaultTableModel table1 = (DefaultTableModel)jTable1.getModel();
        
        try {
         
            while (rs1.next()) {
                table1.addRow(new Object[]{
                    rs1.getString(1),
                    rs1.getString(2),
                    rs1.getString(3),
                    rs1.getString(4),
                    rs1.getDate(5),
                    rs1.getDate(6),
                    rs1.getString(7)});
            }
            
            rs1.close();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        ResultSet rs2 = Select.getData("Select rezervacija.id_rezervacija, smjestaj.vrsta_smjestaja, smjestaj.lokacija, smjestaj.cijena, rezervacija.check_in, rezervacija.check_out, izdavac.username from rezervacija join smjestaj on rezervacija.id_smjestaj = smjestaj.id_smjestaj join izdavac on smjestaj.id_izdavac = izdavac.id_izdavac where rezervacija.potvrda = '1' and DATEDIFF(CURDATE(), rezervacija.check_out) > 0 and rezervacija.id_korisnik = " + Podaci.getId());
        DefaultTableModel table2 = (DefaultTableModel)jTable2.getModel();
       
        
        try {
         
            while (rs2.next()) {
                table2.addRow(new Object[]{
                    rs2.getString(1),
                    rs2.getString(2),
                    rs2.getString(3),
                    rs2.getString(4),
                    rs2.getDate(5),
                    rs2.getDate(6),
                    rs2.getString(7)});
            }
    
            rs2.close();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         
        int index = jTable1.getSelectedRow();
        TableModel table = jTable1.getModel(); 
        String id = table.getValueAt(index,0).toString();
      
        double cijena = 0;
        
        try {
            int a = JOptionPane.showConfirmDialog(null, "Zelite li otkazati rezervaciju?\nU slucaju otkazivanja, bit ce Vam vraceno 95% sredstava.", "Da", JOptionPane.YES_NO_OPTION);
            if(a == 0) {
                
                ResultSet cijenaSql = Select.getData("Select DATEDIFF(rezervacija.check_out, rezervacija.check_in), smjestaj.cijena from rezervacija join smjestaj on smjestaj.id_smjestaj = rezervacija.id_smjestaj where id_rezervacija = " + id);
                
                try {
                    if(cijenaSql.next()) {
                        //System.out.println(cijenaSql.getString(1) + " * " + cijenaSql.getString(2));
                        cijena = cijenaSql.getDouble(1) * cijenaSql.getDouble(2);
                    }
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                
                if (cijena * 0.05 <= Podaci.getBalans(Podaci.getId())) {
                    
                    Podaci.vratiNovac(Podaci.getId(), cijena*0.95);
                    InsertUpdateDelete.setData("delete from rezervacija where id_rezervacija = '" + id + "'", "Rezervacija otkazana!");
                }
                else {
                    JOptionPane.showMessageDialog(null, "Rezervacija ne moze biti otkazana!");
                }
                
                new izvrsene_rezervacije().setVisible(true);
                this.setVisible(false);
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
         int index = jTable2.getSelectedRow();
        TableModel table = jTable2.getModel();
       
        String id = table.getValueAt(index,0).toString();
        
        String input = JOptionPane.showInputDialog("Da li ste zadovoljni smjestajem?\nUpisite ocjenu od 1 do 5:");
        try {
            int ocjena = Integer.parseInt(input);
            
            if (ocjena >=1 && ocjena <= 5) {
                double ukupna_ocjena = 0;
                ResultSet rs = Select.getData("Select ocjena from smjestaj join rezervacija on smjestaj.id_smjestaj = rezervacija.id_smjestaj where id_rezervacija = '" + id + "'");
                try {
                    if(rs.next()) {
                        ukupna_ocjena = rs.getDouble(1);
                        ukupna_ocjena = (ukupna_ocjena + ocjena) /2;
                        InsertUpdateDelete.setData("Update smjestaj set ocjena = '" + ukupna_ocjena + "';", "Uspjesno ocijenjeno!");
                    }
                }
                catch(Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "Molimo upisite ocjenu od 1 do 5!");
            }
       
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocjene se krecu od 1 do 5.");
        }
                
                
        new izvrsene_rezervacije().setVisible(true);
        this.setVisible(false);
   
       
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(izvrsene_rezervacije.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(izvrsene_rezervacije.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(izvrsene_rezervacije.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(izvrsene_rezervacije.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new izvrsene_rezervacije().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
