
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import project.InsertUpdateDelete;
import project.Podaci;
import project.Select;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nihada
 */
public class rezervisanje extends javax.swing.JFrame {

    /**
     * Creates new form rezervisanje
     */
    public rezervisanje() {
        initComponents();
    }
    public int id = prikaz_smjestaja.ID;
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("KORISNIK");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Od:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("do:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Unesite datum od kad do kad želite da rezervišete izabrani smještaj?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Rezerviši smještaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 220, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Unesite broj osoba za koje rezervišete smještaj?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 120, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Odustani");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 130, 30));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 150, 30));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 150, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/g6WHKt.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if (Podaci.getKorisnik() != "") {
        
        try {
        int smjestaj_id = prikaz_smjestaja.ID;
        int korisnik_id = Podaci.getId();
        int br_osoba = Integer.parseInt(jTextField1.getText());
        SimpleDateFormat dateFormat= new SimpleDateFormat("dd/MM/yyyy");
        String in = dateFormat.format(jDateChooser1.getDate());
        String out = dateFormat.format(jDateChooser2.getDate());
        String pom;
        int check=0,zauzet=0, indan, inmjesec, ingodina, outdan, outmjesec, outgodina, danin, mjesecin, godinain, danout, mjesecout, godinaout;
        char[] provjera;
        Date date_in = (Date)jDateChooser1.getDate();
        Date date_out = (Date)jDateChooser2.getDate();
        ResultSet rs=Select.getData("select * from smjestaj where id_smjestaj ='"+smjestaj_id+"'");
        ResultSet rz = Select.getData("select * from rezervacija where id_smjestaj = '"+smjestaj_id+"'");
        provjera = dateFormat.format(jDateChooser1.getDate()).toCharArray();
        //datum kad se želi korisnik da check ina     
        pom = Character.toString(provjera[0])+ Character.toString(provjera[1]);
            danin  = Integer.parseInt(pom);
            pom = Character.toString(provjera[3])+ Character.toString(provjera[4]);
            mjesecin = Integer.parseInt(pom);
            pom = Character.toString(provjera[6])+ Character.toString(provjera[7]) + Character.toString(provjera[8])+ Character.toString(provjera[9]);
            godinain = Integer.parseInt(pom);
            String sendin = Character.toString(provjera[6]) + Character.toString(provjera[7]) + Character.toString(provjera[8])
                    + Character.toString(provjera[9]) + '-' + Character.toString(provjera[3]) + Character.toString(provjera[4])
                            +  '-' + Character.toString(provjera[0]) + Character.toString(provjera[1]);
             //datum kad se želi korisnik da check outa
            provjera = dateFormat.format(jDateChooser2.getDate()).toCharArray();
            pom = Character.toString(provjera[0])+ Character.toString(provjera[1]);
            danout = Integer.parseInt(pom);
            pom = Character.toString(provjera[3])+ Character.toString(provjera[4]);
            mjesecout = Integer.parseInt(pom);
            pom = Character.toString(provjera[6])+ Character.toString(provjera[7]) + Character.toString(provjera[8])+ Character.toString(provjera[9]);
            godinaout = Integer.parseInt(pom);
            String sendout = Character.toString(provjera[6]) + Character.toString(provjera[7]) + Character.toString(provjera[8])
                    + Character.toString(provjera[9]) + '-' + Character.toString(provjera[3]) + Character.toString(provjera[4])
                            +  '-' + Character.toString(provjera[0]) + Character.toString(provjera[1]);
           Date todayDate = new Date(); 
        if (in.isEmpty() || out.isEmpty() || (jTextField1.getText()=="")) {
            JOptionPane.showMessageDialog(null, "Potrebno upisati datume za rezervaciju smještaja.");
            check = 1;
        }
        if( rs.next () & (br_osoba > Integer.parseInt(rs.getString(12)))) {
        JOptionPane.showMessageDialog(null, "Potrebno upisati tačan broj osoba koji se unosio prilikom pretrage.");
        check = 1;
        } else if(date_in.before(todayDate)) {
            JOptionPane.showMessageDialog(null, "Možete rezervisati sobu najranine od sutra.");
            check = 1;
        } else if(date_in.after(date_out)){
        JOptionPane.showMessageDialog(null, "Pogrešan unos datuma.");
        check = 1;
        } else if(mjesecin==mjesecout & danin==danout) {
                JOptionPane.showMessageDialog(null, "Morate rezervisati najmanje jedan dan.");
                check = 1;
        } else {
        while(rz.next()){
            //datum nekog check ina u rezervaciji
            provjera = dateFormat.format(rz.getDate(4)).toCharArray();
            pom = Character.toString(provjera[0])+ Character.toString(provjera[1]);
            indan = Integer.parseInt(pom);
            pom = Character.toString(provjera[3])+ Character.toString(provjera[4]);
            inmjesec = Integer.parseInt(pom);
            pom = Character.toString(provjera[6])+ Character.toString(provjera[7]) + Character.toString(provjera[8])+ Character.toString(provjera[9]);
            ingodina = Integer.parseInt(pom);
            //datum nekog chck outa u rezervaciji
            provjera = dateFormat.format(rz.getDate(5)).toCharArray();
            pom = Character.toString(provjera[0])+ Character.toString(provjera[1]);
            outdan = Integer.parseInt(pom);
            pom = Character.toString(provjera[3])+ Character.toString(provjera[4]);
            outmjesec = Integer.parseInt(pom);
            pom = Character.toString(provjera[6])+ Character.toString(provjera[7]) + Character.toString(provjera[8])+ Character.toString(provjera[9]);
            outgodina = Integer.parseInt(pom);
            if( indan <  outdan ) {
                if( ((danin >= indan & danin <= outdan) || (danout >= indan & danout <= outdan)) & mjesecin == inmjesec & godinain==ingodina) {
                    check = 1;
                    zauzet=1;
                }
            
            } else if(indan > outdan) {
                if(mjesecin == 1 || mjesecin==3 || mjesecin == 5 || mjesecin== 7 || mjesecin==8 || mjesecin== 10 || mjesecin == 12) {
                if( mjesecin == inmjesec & (danin >= indan & danin <= 31) || (danout <= outdan)) {
                check = 1;
                zauzet=1;
                }
                } else if (mjesecin==2) {
                if( mjesecin == inmjesec & (danin >= indan & danin <= 28) || (danout <= outdan)) {
                check = 1;
                zauzet=1;
                }
                } else if(mjesecin == 4 || mjesecin==6 || mjesecin == 9 || mjesecin== 11){
                if( mjesecin == inmjesec & (danin >= indan & danin <= 30) || (danout <= outdan)) {
                check = 1;
                zauzet=1;
                } else {
               if(danin <= outdan ||  danout<=outdan) {
               check = 1;
                zauzet=1;
               }
                }
                }
            } else {
              check = 0;
              zauzet=0;
            }
        }
        }
        if(check == 0) {
            double cijena = 0;
            boolean popust = false;
            ResultSet cijenaSql = Select.getData("Select DATEDIFF('" + sendout + "', '" + sendin + "'), cijena from smjestaj");
                
                try {
                    if(cijenaSql.next()) {
                        System.out.println(cijenaSql.getString(1) + " * " + cijenaSql.getString(2));
                        
                        ResultSet brojRezervacija = Select.getData("select count(*) from rezervacija where potvrda = '1' and id_korisnik = " + Podaci.getId());
                        try {
                            if (brojRezervacija.next()) {
                                int brojRez = brojRezervacija.getInt(1);
                                if (brojRez >= 5)
                                    popust = true;
                                System.out.println("broj " + brojRez);
                            }
                        }
                        catch(Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                        if (popust) {
                            cijena = cijenaSql.getDouble(1) * cijenaSql.getDouble(2) * 0.9;
                            JOptionPane.showMessageDialog(null, "Rezervisali ste vise od 5 puta i ostvarili popust od 10%!");
                        }
                        else
                            cijena = cijenaSql.getDouble(1) * cijenaSql.getDouble(2);
                            
                    }
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                
                if (cijena <= Podaci.getBalans(Podaci.getId())) {
                    InsertUpdateDelete.setData("insert into rezervacija (id_smjestaj, id_korisnik, check_in, check_out, br_osoba, potvrda) values ('" + smjestaj_id + "', '" + korisnik_id + "', '" + sendin + "', '" + sendout + "', '" + br_osoba + "','0')","Čekanje na odobrenje rezervacije.");       
                } 
                else {
                    JOptionPane.showMessageDialog(null, "Nemate dovoljno sredstava na racunu! Ne moze se izvrsiti rezervacija!");
                }
        }
        else if(zauzet == 1){
        
            JOptionPane.showMessageDialog(null, "Smještaj je zauzet!");
            zauzet = 0;
        }
        }        
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        }
        else {
            JOptionPane.showMessageDialog(null, "Niste prijavljeni!");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new prikaz_smjestaja().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rezervisanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rezervisanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rezervisanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rezervisanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rezervisanje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
