
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
//import static manageroom.f;
import project.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class smjestajDelUp extends javax.swing.JFrame {

   
    /**
     * Creates new form smjestajDelUp
     */
    public smjestajDelUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vrsta smjestaja:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 170, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Velicina:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 170, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Sprat");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 170, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Lokacija");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 170, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Kapacitet");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 170, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cijena");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 170, 30));

        jCheckBox1.setBackground(new java.awt.Color(102, 102, 255));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Parking");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jCheckBox4.setBackground(new java.awt.Color(102, 102, 255));
        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Rostilj");
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jCheckBox2.setBackground(new java.awt.Color(102, 102, 255));
        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Bazen");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        jCheckBox5.setBackground(new java.awt.Color(102, 102, 255));
        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("WiFi");
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        jCheckBox3.setBackground(new java.awt.Color(102, 102, 255));
        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Balkon");
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jCheckBox6.setBackground(new java.awt.Color(102, 102, 255));
        jCheckBox6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setText("Kucni ljubimci");
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Izmijeni");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 80, 30));

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("Izbrisi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 80, 30));

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("Odustani");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 90, 30));

        jButton4.setText("Učitaj");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    public static String PATH;
    public static File f;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String vrsta_smjestaja, cijena, lokacija, sprat, velicina, kapacitet, kucni_ljubimci, rostilj, balkon, bazen, wifi, parking;
        vrsta_smjestaja = jTextField7.getText();
        velicina = jTextField8.getText();
        kapacitet = jTextField11.getText();
        lokacija = jTextField10.getText();
        sprat = jTextField9.getText();
        cijena = jTextField12.getText();
        String novi_path = PATH.replace("\\", "/");
        //String novi_path = manageroom.PATH.replace("\\", "/");
        
        if (jCheckBox1.isSelected())
            parking = "1";
        else parking = "0";
        
        if (jCheckBox2.isSelected())
            bazen = "1";
        else bazen = "0";

        if (jCheckBox3.isSelected())
            balkon = "1";
        else balkon = "0";

        
        if (jCheckBox4.isSelected())
            rostilj = "1";
        else rostilj = "0";
        
        if (jCheckBox5.isSelected())
            wifi = "1";
        else wifi = "0";
        
        if (jCheckBox6.isSelected())
            kucni_ljubimci = "1";
        else kucni_ljubimci = "0";
                
        if (vrsta_smjestaja=="" || velicina=="" ||  cijena=="" || lokacija=="" || kapacitet=="" || sprat=="") {
            JOptionPane.showMessageDialog(null, "Potrebno upisati sve podatke");
        }
        else {                                                                                                                                                                                                                 
            
                try {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                   InsertUpdateDelete.setData("update smjestaj set vrsta_smjestaja = '"+ vrsta_smjestaja + "', velicina = '"+ velicina + "', parking = '" +parking + "', wifi = '" + wifi + "', balkon = '" + balkon + "', bazen = '" + bazen + "', kucni_ljubimci = '" + kucni_ljubimci + "', rostilj = '" + rostilj + "', sprat = '" + sprat + "', id_izdavac = '" + Podaci.getId() + "', slika = '"+"LOAD_FILE(\""+novi_path+"\")" + "', kapacitet = '" + kapacitet + "', cijena = '" + cijena + "', lokacija = '" + lokacija  + "', status = '0' where id_smjestaj = " + Podaci.getId_smjestaj(), "Cekanje na odobrenje admina!");
                                    //InsertUpdateDelete.setData("insert into smjestaj (vrsta_smjestaja, velicina, parking, wifi, balkon, bazen, kucni_ljubimci, rostilj, sprat, id_izdavac, kapacitet, cijena, lokacija, slika, status) values ('" + vrsta_smjestaja + "', '" + velicina + "', '" + parking + "', '" + wifi + "', '" + balkon + "', '" + bazen + "', '" + kucni_ljubimci + "', '" + rostilj + "', '" + sprat + "', '" + Podaci.getId() + "', '" + kapacitet + "', '" + cijena + "', '" + lokacija + "','"+ "LOAD_IMAGE(" +  PATH   +  ")" +     "','"+    '5'+      "',  '1')", "Cekanje na odobrenje admina!");
           /*         InsertUpdateDelete.setData("update smjestaj set slika =  " + "LOAD_FILE(\""+novi_path+"\")", "");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookingBaza", "root", "1009Kanita");
                    FileInputStream fin=new FileInputStream(manageroom.f);
                    int len=(int)manageroom.f.length();

                    PreparedStatement ps=con.prepareStatement("update smjestaj set slika = ? where id_smjestaj = " + Podaci.getId_smjestaj());
                    ps.setBinaryStream(1, fin, len);
                    int status=ps.executeUpdate();
             */  
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookingBaza", "root", "hotmail7110");
            FileInputStream fin=new FileInputStream(f);
            int len=(int)f.length();
            
             PreparedStatement ps=con.prepareStatement("update smjestaj set slika = ? where id_smjestaj = " + Podaci.getId_smjestaj());
            ps.setBinaryStream(1, fin, len);
            int status=ps.executeUpdate();
            }       
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
    }
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        try {
                
                ResultSet rezervacije = Select.getData("select * from rezervacija where id_smjestaj =" + Podaci.getId_smjestaj());
                try {
                    
                    if (rezervacije.next()) {
                        int id_rezervacija = rezervacije.getInt(1);
                        ResultSet cijenaSql = Select.getData("Select DATEDIFF(rezervacija.check_out, rezervacija.check_in), smjestaj.cijena, id_korisnik from rezervacija join smjestaj on smjestaj.id_smjestaj = rezervacija.id_smjestaj where id_rezervacija = " + id_rezervacija);
                        double cijena = 0;
                        
                        try {
                            if(cijenaSql.next()) {
                                //System.out.println(cijenaSql.getString(1) + " * " + cijenaSql.getString(2));
                                cijena = cijenaSql.getDouble(1) * cijenaSql.getDouble(2);
                                Podaci.vratiNovac(cijenaSql.getInt(3), cijena);
                            }
                        }
                        catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                        InsertUpdateDelete.setData("delete from poruka where id_rezervacija = " + id_rezervacija, "");
                        
                    }
                }
                catch(Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
               
                
                InsertUpdateDelete.setData("delete from rezervacija where id_smjestaj = " + Podaci.getId_smjestaj(), "");
                InsertUpdateDelete.setData("delete from smjestaj where id_smjestaj = " + Podaci.getId_smjestaj(), "Smjestaj je izbrisan!");

            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Podaci.setId_smjestaj(-1);
        new manageroom().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
        ResultSet smjestaj = Select.getData("Select * from smjestaj where id_smjestaj = " + Podaci.getId_smjestaj());
        
        try {
            if (smjestaj.next()) {
                jTextField7.setText(smjestaj.getString(2));
                jTextField8.setText(smjestaj.getString(3));
                jTextField9.setText(smjestaj.getString(10));
                jTextField10.setText(smjestaj.getString(14));
                jTextField11.setText(smjestaj.getString(12));
                jTextField12.setText(smjestaj.getString(13));
                
                
                if (smjestaj.getBoolean(4))
                    jCheckBox1.setSelected(true);
                if (smjestaj.getBoolean(5))
                    jCheckBox5.setSelected(true);
                if (smjestaj.getBoolean(6))
                    jCheckBox3.setSelected(true);
                if (smjestaj.getBoolean(7))
                    jCheckBox2.setSelected(true);
                if (smjestaj.getBoolean(8))
                    jCheckBox6.setSelected(true);
                if (smjestaj.getBoolean(9))
                    jCheckBox4.setSelected(true);
                
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        //jTextField1.setText(manageroom.PATH);
    }//GEN-LAST:event_formComponentShown

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
             f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            PATH = filename;
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(smjestajDelUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(smjestajDelUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(smjestajDelUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(smjestajDelUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new smjestajDelUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
